// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EF.Models
{
    public partial class ImportReportKeywordDaily
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public string CampaignName { get; set; }
        public string AdGroupName { get; set; }
        public string Keyword { get; set; }
        public int Clicks { get; set; }
        public int Impressions { get; set; }
        public decimal Spend { get; set; }
        public decimal Days7TotalSales { get; set; }
        public int Days7TotalOrders { get; set; }
        public int Days7TotalUnits { get; set; }
        public decimal Days7ConversionRate { get; set; }
        public int Days7SameSkuUnits { get; set; }
        public int Days7OtherSkuUnits { get; set; }
        public decimal Days7SameSkuSale { get; set; }
        public decimal Days7OtherSkuSale { get; set; }
    }
}